---
name: Metrics
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          # Commit Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # Languages
          plugin_languages: yes
          commits_authoring: aw1cks@users.noreply.github.com
          # Stars
          plugin_stars: yes
          plugin_stars_limit: 4
          # Music
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 4
          plugin_music_played_at: yes
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          # Pagespeed
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: no
          plugin_pagespeed_screenshot: no
          plugin_pagespeed_url: .user.website
